version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
